### ISSUE TITLE
plr AND PostgreSQL 9.5

### ISSUE THREAD

**Issue by gmusumeci** [jconway/plr#17]
I'm running postgres 9.5 on windows 10.
I downloaded plr 8.3.0.16.
I followed instructions about configuration of enviroment variables according to the file install.txt included in the zip.

When I try to create extension plr in my database I get the following error:

ERROR:  incompatible library "C:/Program Files/PostgreSQL/9.5/lib/plr.dll": version mismatch
DETAIL:  Server is version 9.5, library is version 9.4.

********** Error **********

ERROR: incompatible library "C:/Program Files/PostgreSQL/9.5/lib/plr.dll": version mismatch
SQL state: XX000
Detail: Server is version 9.5, library is version 9.4.

**Comment by davecramer** [comment]
Where did you get the library from ?

**Comment by gmusumeci** [comment]
I get them from
http://www.joeconway.com/plr/

**Comment by davecramer** [comment]
Ah, ok, so we have to build a new dll for 9.5. I'm trying to sort that out
right now, stay tuned!

Dave Cramer

**Comment by gmusumeci** [comment]
I surely will be tuned! Bye!!

**Comment by yipeng** [comment]
I am also waiting for this. Is there any workaround other than downgrading to 9.4? Thanks!

**Comment by davecramer** [comment]
unfortunately no.

Dave Cramer

**Comment by hwmattk** [comment]
Is this specific to Windows builds, or common to all PG 9.5 platforms?

**Comment by davecramer** [comment]
Just windows builds. I am working on it, but windows builds are
"interesting" in the Chinese proverb sense of the word

Dave Cramer

**Comment by davecramer** [comment]
Hi, can you try the file attached to https://github.com/postgres-plr/plr/issues/1 and let me know if it works

**Comment by yipeng** [comment]
Worked for me when I used R 3.2.0 but not 3.2.5. Thanks for this. It did something for my well being.

**Comment by salizadeh** [comment]
Hi Joe,
How could find PL/R compatible version for PostgreSQL 9.6, because I had an  following error when I ran CREATE EXTENSION plr; 
 
ERROR:  incompatible library "C:/Program Files/PostgreSQL/9.6/lib/plr.dll": version mismatch
DETAIL:  Server is version 9.6, library is version 9.5.
********** Error **********

**Comment by davecramer** [comment]
hi @salizadeh this repo has been deprecated see https://github.com/postgres-plr/plr/releases/tag/REL8_3_0_17

**Comment by salizadeh** [comment]
Thank you so much.
