### ISSUE TITLE
xx/prl.dll,The specified module could not be found. SQL state: 58P01

### ISSUE THREAD

**Issue by Ullix-xl** [jconway/plr#29]
I'm following the instructions, but when i excute command: CREATE EXTENSION plr;  I get following a message,
 ERROR :无法加载库 "E:/APPS/POSTgresql/15/lib/plr.dll": The specified module could not be found.SQL state: 58P01.  
I'm sure plr.dll is there. I can't fix it, please help.

**Comment by davecramer** [comment]
the proper place to log this error is https://github.com/postgres-plr/plr but 9 times out of ten the issue is you do not have R installed

**Comment by Ullix-xl** [comment]
thanks you davecramer, R is installed. i excute R command : R.home(),
I get this message: D:/Apps/R-4.2.3. 
I following installtion :https://github.com/postgres-plr/plr/blob/master/userguide.md#installation.
but get this error

**Comment by davecramer** [comment]
please move this to the other repo
